# Generated by Django 3.1.5 on 2021-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cidade_famoso_localiza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='descricao',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='famoso',
            name='descricao',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
