# Generated by Django 3.1.5 on 2021-01-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210126_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='wikip',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='famoso',
            name='wikip',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='famoso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
