# Generated by Django 3.1.5 on 2021-01-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210128_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='wikip',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='famoso',
            name='wikip',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
